name: 'CI'
on:
  - push
  - pull_request

env:
  RCDS_RCTF_URL: https://ctf.itemize.no/
  RCDS_RCTF_TOKEN: ${{ secrets.RCDS_RCTF_TOKEN }}

jobs:
  deploy:
    runs:
      using: 'docker'
      image: 'Dockerfile'
