name: 'CI'
on:
  - push
  - pull_request

env:
  RCDS_RCTF_URL: https://ctf.itemize.no/
  RCDS_RCTF_TOKEN: ${{ secrets.RCDS_RCTF_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build and deploy docker image
        run: > 
           docker build --build-arg token=${RCDS_RCTF_TOKEN} . -t foobar -f Dockerfile 
      - name: Run docker image
        run: >
           docker run foobar
