name: "CI"
on:
  - push
  - pull_request

env:
  RCDS_RCTF_URL: https://ctf.itemize.no/
  RCDS_RCTF_TOKEN: ${{ secrets.RCDS_RCTF_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the inspector Docker image
        run: |
          docker build ./web/inspector --tag ghcr.io/shirajuki/itemizectf:inspector
          docker run ghcr.io/shirajuki/itemizectf:inspector
          docker push ghcr.io/shirajuki/itemizectf:inspector

      - name: Build the robots Docker image
        run: |
          docker build ./web/robots --tag ghcr.io/shirajuki/itemizectf:robots
          docker run ghcr.io/shirajuki/itemizectf:robots
          docker push ghcr.io/shirajuki/itemizectf:robots
