name: 'CI'
on:
  - push
  - pull_request

env:
  RCDS_RCTF_URL: https://ctf.itemize.no/
  RCDS_RCTF_TOKEN: ${{ secrets.RCDS_RCTF_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Docker build and publish to ghcr.io
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Deploy Container
        env:
          URL: ${{ secrets.DEPLOY_UPDATE_WEBHOOK }}
        run: 'curl -i -X POST "$URL"'

  deploy:
    stage: deploy
    when: manual
    environment:
      name: production
    script:
      - rcds deploy
