name: 'CI'
on:
  - push
  - pull_request

env:
  RCDS_RCTF_URL: https://ctf.itemize.no/
  RCDS_RCTF_TOKEN: ${{ secrets.RCDS_RCTF_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Docker build and publish to ghcr.io
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build and deploy docker image
        run: > 
           docker build --build-arg token=${RCDS_RCTF_TOKEN} . -t foobar -f Dockerfile 
      - name: Run docker image
        run: >
           docker run foobar
