name: 'CI'
on:
  - push
  - pull_request

env:
  RCDS_RCTF_URL: https://ctf.itemize.no/
  RCDS_RCTF_TOKEN: ${{ secrets.RCDS_RCTF_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install rcds
        run: |
          python -m pip install --upgrade pip
          pip install rcds

      - name: Deploy to production
        run: rcds deploy
